### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#1]
![screencapture-localhost-5000-2019-10-11-18_21_19](https://user-images.githubusercontent.com/6862485/66688285-fa762c00-ec53-11e9-82b7-de193467726c.png)

**Tasks**
- [x] SSO via Auth0
- [x] Sign up and Login via Email/Password
- [x] Form Validation
- [x] Form Submission Errors 
- [x] Redirection to `/workspaces` on success
- [x] Authenticated state persists between browser windows
- [x] `/token` route to view and copy auth token
- [x] Responsive - mobile & tablet
- [x] Cypress tests are created & pass

**Technicalities**
- [x] `publicSignups` enabled/disabled
- [x] `emailConfirmation` enabled/disabled
- [x] Configurable Auth0 entry points
- [x] CLI auth redirects to `/token`

**Comment by samblackk** [comment]
This Epic is completed as Feature Complete. Closing the issue.
