### ISSUE TITLE
Deployment Configure

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#10]
![screencapture-localhost-5000-workspaces-ck1qhkkny002a096789mwlr9w-deployments-ck1qj9uum04y50967tprd59ll-config-2019-10-14-11_01_09](https://user-images.githubusercontent.com/6862485/66761420-f889b400-ee71-11e9-9395-12604f50d703.png)

**Tasks**
- [ ] Total Cluster Resources bar graph with breakdowns in AU
- [ ] Webserver config
- [ ] Scheduler config 
- [ ] Extra Capacity config 
- [ ] Meta Config - label & description
- [ ] Environment Variables 
- [ ] Deprovision Deployment
- [ ] Form Validation
- [ ] Form Submit Errors
- [ ] Route contains `workspaceUuid` and `deploymentUuid`
- [ ] Responsive - mobile & tablet 

**Technicalities**
- [ ] Celery executor shows Celery worker options
