### ISSUE TITLE
Deployment Usage

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#11]
![screencapture-localhost-5000-workspaces-ck1qhkkny002a096789mwlr9w-deployments-ck1qj9uum04y50967tprd59ll-usage-2019-10-14-11_05_31](https://user-images.githubusercontent.com/6862485/66761743-97161500-ee72-11e9-8fb0-0d63997ff233.png)

Based on this feature request: https://github.com/astronomer/issues/issues/209

**Tasks**
- [ ] Daily usage table
- [ ] Route contains `workspaceUuid` and `deploymentUuid`
- [ ] Responsive - mobile & tablet 

**Technicalities** 
None.
