### ISSUE TITLE
Deployment Metrics

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#12]
![screencapture-localhost-5000-workspaces-ck1qhkkny002a096789mwlr9w-deployments-ck1qj9uum04y50967tprd59ll-metrics-2019-10-14-11_09_08](https://user-images.githubusercontent.com/6862485/66761971-10156c80-ee73-11e9-93b9-f187b3d989ee.png)

**Tasks**
- [ ] Deployment status: Deployment, Scheduler
- [ ] Deployment Container status table 
- [ ] Task Stream 
- [ ] Database Connections: Total Database Connections, Total Waiting Clients
- [ ] Scheduler Heartbeat
- [ ] Dagbag Size
- [ ] Zombies Killed
- [ ] Task Success Rate
- [ ] Task Fail Rate
- [ ] Quotas: Pods, CPU, Memory
- [ ] Resource Utilization: CPU Usage, Memory Usage, Network Rx, Network Tx
- [ ] Filter by time: last 15 mins to last 14 days 
- [ ] Route contains `workspaceUuid` and `deploymentUuid`
- [ ] Responsive - mobile & tablet 

**Technicalities**
None.
