### ISSUE TITLE
Deployment Logs

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#13]
![screencapture-localhost-5000-workspaces-ck1qhkkny002a096789mwlr9w-deployments-ck1qj9uum04y50967tprd59ll-logs-2019-10-14-11_13_53](https://user-images.githubusercontent.com/6862485/66762313-bd888000-ee73-11e9-86d0-9f390913676e.png)

**Tasks**
- [ ] Virtual terminal 
- [ ] Colored logs
- [ ] Route contains `workspaceUuid` and `deploymentUuid`
- [ ] Responsive - mobile & tablet 

**Technicalities** 
- [ ] Search, sort, and filter logs
- [ ] Scroll jumping/jank in container
- [ ] Performance when rendering 500+ logs
