### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#2]
<img width="909" alt="Screen Shot 2019-10-16 at 8 39 50 PM" src="https://user-images.githubusercontent.com/6862485/66968884-1ebb7980-f055-11e9-9efb-d0b169a1f4ed.png">

**Tasks**
- [x] Workspace list
- [x] Button to "add new workspace"
- [ ] "No Workspaces" illustrated screen @Inkdryer
- [x] Responsive - mobile & tablet
- [x] Cypress tests are created & pass

**Technicalities**
None.
