### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#20]
**Tasks**
- [x] List of users on the platform
- [x] Invite user button
- [ ] Responsive - mobile & tablet 
- [ ] Cypress tests are created & pass

**Technicalities**
- Can never have a "no users" screen, as the auth user will always count as 1 user in the list.
