### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#22]
![screencapture-localhost-5000-activity-2019-10-14-11_47_18](https://user-images.githubusercontent.com/6862485/66764729-689b3880-ee78-11e9-82cd-d0fde633987f.png)

This is a new feature/page entirely. 
Idea is provide a feed of activity on the platform.

**Tasks**
- [ ] Feed 
- [ ] Task metrics
- [ ] Filter and sort options
- [ ] Responsive - mobile & tablet
- [ ] Cypress tests are created & pass

**Technicalities**
- [ ] User permissions - who can see what?
