### ISSUE TITLE
Overall UX/UI

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#23]
**Tasks**
- [ ] Responsive - mobile & tablet 
- [ ] Footer version is pulling the latest from helm
- [ ] User menu opens when clicking on sidebar nav user chip
- [ ] Menus have accurate active states 
- [ ] Transitions
- [ ] Loading indicators 

**Platforms**
- [ ] Browser compatibility - latest 2 - chrome, edge, firefox, safari
- [ ] Accessibility at least 80%
