### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#3]
**Story**
As a user, I want to get a high-level overview of all the deployments in a workspace. I also want to manage users and service accounts. I need to be able to adjust the workspace settings. A quick way to create a deployment in that workspace is needed.

**Tasks**
- [ ] Deployment list 
- [ ] "No Deployments" illustrated screen @Inkdryer 
- [ ] Create a deployment button 
- [ ] Workspace specific-nav: deployments, config, user, service accounts 
- [ ] Route contains `workspaceUuid`

**Technicalities** 
None.
