### ISSUE TITLE
Workspace - Add New

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#4]
![screencapture-localhost-5000-workspaces-create-2019-10-11-18_26_14](https://user-images.githubusercontent.com/6862485/66688446-a0299b00-ec54-11e9-969c-11b2a3cbc102.png)

**Story**
As a user, I want to be able to make a new workspace quickly. I also want to add users to the workspace either by selected from the current list of users on the platform or inviting a new user via email. 

**Tasks**
- [ ] Explanation of what a workspace is
- [ ] Label & Description fields
- [ ] Add Users field
- [ ] Form Validation
- [ ] Form Errors
- [ ] Redirects to `/workspaces` when successful
- [ ] Responsive - mobile & tablet

**Technicalities**
None.
