### ISSUE TITLE
Workspace Settings

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#5]
![screencapture-localhost-5000-workspaces-ck1l49w41165w07704n6amwyw-config-2019-10-11-18_29_53](https://user-images.githubusercontent.com/6862485/66688552-22b25a80-ec55-11e9-99a8-386714218d7c.png)

**Story**
As a user, I want to be able to update the workspace name (label) and description. I also need a way to delete the workspace. 

**Tasks**
- [ ] Form includes label and description fields
- [ ] Form Validation
- [ ] Form Submit Errors
- [ ] Delete button with notice

**Technicalities**
- [ ] Cannot delete while deployments are active (need to delete deploys first)
