### ISSUE TITLE
Workspace Billing

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#8]
![screencapture-localhost-5000-workspaces-ck1l49w41165w07704n6amwyw-billing-2019-10-11-19_52_18](https://user-images.githubusercontent.com/6862485/66690848-c1908400-ec60-11e9-8fa9-977b7b6b8db5.png)

**Story**
As a user, I need a clean - simple - dashboard to manage the billing of the workspace. I also need to see details of the trial and how much I will be charged per month. 

**Tasks**
- [ ] Trial Information
- [ ] Current monthly charge
- [ ] Stripe CC form
- [ ] Form Validation
- [ ] Form Submit Errors
- [ ] Route contains `workspaceUuid`
- [ ] Responsive - mobile & tablet

**Technicalities**
- [ ] Conditional trial information
