### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by samblackk** [astronomer/new-orbit#9]
![screencapture-localhost-5000-workspaces-ck1l49w41165w07704n6amwyw-deployments-ck1l88doi17nz0770xglqcbal-2019-10-11-22_21_55](https://user-images.githubusercontent.com/6862485/66693464-fad3ee80-ec76-11e9-9779-91f89bd8463d.png)

**Tasks**
- [ ] Navigational Container: overview, configure, usage, metrics, logs, alerts, service accounts
- [ ] Heartbeat graph
- [ ] Links to sources (airflow, celery, flower, etc)
- [ ] Route contains `workspaceUuid` and `deploymentUuid`
- [ ] Responsive - mobile & tablet

**Technicalities**
- [ ] Need to pull just the heartbeat metric
